/**
 * Page Builder
 * 
 * A page definition contains :
 *  - the page definition as html (page.html),
 *  - necessary javascripts       (page.js),
 *  - language definitions        (i18n/*.json)
 * 
 * 
 * As the pages defines also the structure of the menu,
 * it is necessary to join them in the correct order (!)
 * 
 * Therefore a file "pages.json" in the root of the project is used.
 * 
 * {
 *      out: {
 *          path:        (default is src/web)
 *          pageFile:    (default is pages.html)
 *          pageScript:  (default is pages.js)
 *      }
 *      include: [
 *              "pathToPageDir",
 *              "pathToPages/*"
 *          ] 
 *              
 *              
 * }
 */
const fs = require("fs");
const path = require("path");

const ProgName = "pageBuilder";
const ProgVersion = "1.0.0";

const CTRL_FILE = "pages.json";
const PAGE_HTML = "page.html";
const PAGE_SCRIPT = "page.js";
const PAGE_I18N = "i18n";

const DEFAULTS = {
    "out": {
        "path": "src/web",
        "pageFile": "pages.html",
        "pageScript": "pages.js",
        "i18nLoc" : "i18n",
        "writePageRegistration": true
    },
    "include": {},
    "getHtmlTargetName": function() {
        return(path.join(Settings.out.path,Settings.out.pageFile));
    },
    "getScriptTargetName": function() {
        return(path.join(this.out.path,this.out.pageScript));
    },
    "getLanguagePath": function() {
        let strPath = path.join(this.out.path,this.out.i18nLoc);
        if(!fs.existsSync(strPath)) fs.mkdirSync(strPath);
        return(strPath);
    }
}

const HTML_PREAMBLE = [
    "<!-- ",
    " ***************************************************************************",
    " * This file is generated by " + ProgName + " v" + ProgVersion ,
    " * Do not edit this file, it will be overwritten by the pageBuilder script.",
    " * The pageBuilder is part of the PLibESPV1 project.",
    " * Build date: " + new Date().toISOString(),
    " * Build context: " + getProjectName(),
    " *************************************************************************** -->",
    ""
];
const SCRIPT_PREAMBLE = [
    "/***************************************************************************",
    " * This file is generated by " + ProgName + " v" + ProgVersion ,
    " * Do not edit this file, it will be overwritten by the pageBuilder script.",
    " * The pageBuilder is part of the PLibESPV1 project.",
    " * Build date: " + new Date().toISOString(),
    " * Build context: " + getProjectName(),
    " ***************************************************************************/",
    ""
];

var Settings = {};

var Status = {
    "numHTML": 0,
    "numScript": 0,
    "numLanguages": 0,
    "numErrors": 0,
    "bCreatePageRegistration": false
}

function loadControlFile(strCtrlFile) { 
    if(!strCtrlFile) {
        if(process.argv.length > 2) {
            strCtrlFile = process.argv[2];
        } else {    
            strCtrlFile = CTRL_FILE;
        }
    }
    console.log(" - loading control file : " +  strCtrlFile );
    let strCtrl = fs.readFileSync(strCtrlFile)
    let oCtrl = JSON.parse(strCtrl);
    Settings = { ...DEFAULTS, ...oCtrl};
    Settings.out = {...DEFAULTS.out, ...oCtrl.out}
}

function getProjectName() {
    let strName = path.basename(process.cwd());
    return(strName);
}

function joinHtmlPage(strPagePath) {
    let strInput = path.join(strPagePath,PAGE_HTML);
    if(fs.existsSync(strInput)) {
        let strOut = Settings.getHtmlTargetName();
        console.log("   -> appending HTML to : " + strOut);
        let strData = fs.readFileSync(strInput);
        fs.appendFileSync(strOut,strData);
        Status.numHTML++;
    }
}


let tPageHandlerRegistration = [];

function joinScriptPage(strPagePath) {
    let strInput = path.join(strPagePath,PAGE_SCRIPT);
    if(fs.existsSync(strInput)) {
        let strOut = Settings.getScriptTargetName();
        console.log("   -> appending Script to : " + strOut);
        let strData = fs.readFileSync(strInput);
        fs.appendFileSync(strOut,strData);
        Status.numScript++;

        let oRXPageRegistration = new RegExp('@PageBuilder:register\((?<id>.*),(?<class>.*)\)',"g");
        let oRXResult = oRXPageRegistration.exec(strData);
        if(oRXResult) {
            Status.bCreatePageRegistration = true;
            let strID = oRXResult.groups.id.startsWith("(") ? oRXResult.groups.id.substring(1) : oRXResult.groups.id;
            let strClass = oRXResult.groups.class.endsWith(")") ? oRXResult.groups.class.substring(0,oRXResult.groups.class.length-1) : oRXResult.groups.class;
            console.log("   -> Page registration found, will register page handler:" + strID + " with " + strClass);
            tPageHandlerRegistration.push({ "id": strID, "class": strClass });
        }

    }
}

function writePageHandlerRegistration() {
    if(Status.bCreatePageRegistration && Settings.out.writePageRegistration === true) {
        let strOut = Settings.getScriptTargetName();
        console.log("   -> writing page handler registration to : " + strOut);
        let fd = fs.openSync(strOut, 'a');
        if(fd) {
            fs.writeSync(fd, "\n// Page Handler Registration\n");
            fs.writeSync(fd, "function registerPageHandler(pApp)\n");
            tPageHandlerRegistration.forEach((oPageHandler) => {
                console.log(oPageHandler);
                fs.writeSync(fd, `{\n    pApp.registerPageHandler("${oPageHandler.id}",new ${oPageHandler.class}(pApp));\n`);
            });
            fs.writeSync(fd, "}\n");
            fs.writeSync(fd, "\n// End of Page Handler Registration\n");
            fs.close(fd);
            console.log("   -> Page Handler registration written.");
        }
    }
}

function getJsonFromFile(strFile) {
    let oData = {};
    if(fs.existsSync(strFile)) {
        let strData = fs.readFileSync(strFile);
        oData = JSON.parse(strData);
    }
    return(oData);
}

function joinLanguages(strPagePath) {
    let strInputPath = path.join(strPagePath,PAGE_I18N); {
        let oRX = new RegExp("^[a-z]{2}\.json$")
        if(fs.existsSync(strInputPath)) {
            fs.readdirSync(strInputPath).forEach((strFile) => {
                if(oRX.test(strFile)) {
                    console.log("   -> joining language : " + strFile);
                    // Join the language....
                    let strTargetFile = path.join(Settings.getLanguagePath(),strFile);
                    let oTarget = getJsonFromFile(strTargetFile);

                    let strInputFile = path.join(strInputPath, strFile);
                    let oInput = getJsonFromFile(strInputFile);
                    let oResult = {...oTarget,...oInput}
                    fs.writeFileSync(strTargetFile,JSON.stringify(oResult,null,2));

                    Status.numLanguages++;
                }
            });
        }
    }
}


function removeTargets() {
    if(fs.existsSync(Settings.getHtmlTargetName())) fs.rmSync(Settings.getHtmlTargetName())
    if(fs.existsSync(Settings.getScriptTargetName())) fs.rmSync(Settings.getScriptTargetName())
}


function prepareAndWritePreample() {
    let strPath = Settings.out.path;
    if(!fs.existsSync(strPath)) fs.mkdirSync(strPath);
    let strHtmlFileName = Settings.getHtmlTargetName();
    let fd = fs.openSync(strHtmlFileName, 'w');
    if(fd) {
        console.log(" - writing HTML preamble to : " + strHtmlFileName);
        HTML_PREAMBLE.forEach((line) => {
            fs.writeSync(fd, line + "\n");
        });
        fs.close(fd);
    };
    
    let strScriptFileName = Settings.getScriptTargetName();
    fd = fs.openSync(strHtmlFileName, 'w');
    if(fd) {
        console.log(" - writing SCRIPT preamble to : " + strScriptFileName);
        SCRIPT_PREAMBLE.forEach((line) => {
            fs.writeSync(fd, line + "\n");
        });
        fs.close(fd);
    };
}

function processPages() {
    let strPath = Settings.out.path;
    if(!fs.existsSync(strPath)) fs.mkdirSync(strPath);
    for(let strName of Settings.include) {
        console.log(" - processing : " + strName);
        joinHtmlPage(strName);
        joinScriptPage(strName);
        joinLanguages(strName);
    }
}

function printStatus() {
    console.log("=======================================");
    console.log(" pageBuilder - Status");
    console.log("=======================================");
    console.log(" - Project name          : " + getProjectName());
    console.log(" - Output path           : " + Settings.out.path);
    console.log(" - HTML target file      : " + Settings.getHtmlTargetName());
    console.log(" - Script target file    : " + Settings.getScriptTargetName());
    console.log(" - Language path         : " + Settings.getLanguagePath());
    console.log(" - HTML pages joined     : " + Status.numHTML);
    console.log(" - Script pages joined   : " + Status.numScript);
    console.log(" - Languages joined      : " + Status.numLanguages);
    if(Status.numErrors > 0) {
        console.error(" - Errors encountered    : " + Status.numErrors);
    } else {
        console.log(" - No errors encountered.");
    }
}

console.log("=======================================");
console.log(`${ProgName} - v${ProgVersion}`)
console.log("=======================================");
loadControlFile();
removeTargets();
prepareAndWritePreample();
processPages();
writePageHandlerRegistration();
printStatus();
